### ISSUE TITLE
Faile to new Image in x86 macOS, node version 20.12.1

### ISSUE THREAD

**Issue by SteveWooo** [mmomtchev/magickwand.js#129]
Hello author, I have encountered some error that make the project can not proceed normally, so I have to come here for help.

After I installed node-magickwand via npm on an x86 mac, I executed the following code: 

```
const { Magick } = require('magickwand.js')
async function main() {
    const filePath = '/Users/deadfish/Documents/project/deadfish/Photography2Client/testFiles/DSC_6880.NEF'
    const largeWand = new Magick.Image(filePath)
}
main()
```

And here is the error information:

```
/test.js:4
    const largeWand = new Magick.Image(filePath)
                      ^

Error: node: unable to open image '/var/folders/s7/h94j1mz54_bd7ss0xk1h891r0000gn/T/magick-u16WoVnI3F6lzl0HbDLctNjtbwfzfrTU.ppm': No such file or directory @ error/blob.c/OpenBlob/3571
    at main (/Users/deadfish/Documents/project/deadfish/Photography2Client/p2p-pick/photographyClient/test.js:4:23)
    at Object.<anonymous> (/Users/deadfish/Documents/project/deadfish/Photography2Client/p2p-pick/photographyClient/test.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.1
```

It works fine on windows, but faile on macOS, version Monterry 12.6.2(21G320).

I understand that I can use magick in software by calling system commands, but this is too cumbersome for the user, so hopefully We can find the cause of this error.

**Comment by mmomtchev** [comment]
Have you tried using a small wand, maybe it is a size problem?
