### ISSUE TITLE
install failed with "error: Package '***********' not found"

### ISSUE THREAD

**Issue by Saraiby** [mmomtchev/magickwand.js#266]
## Issue describe
Install failed. error messege: "error: Package '***********' not found". The fail package is random.

## Reproduce
1. run 'npm install magickwand.js'.
2. Failed after a while.

## Detail log
```
npm silly placeDep ROOT safe-buffer@5.2.1 OK for: tunnel-agent@0.6.0 want: ^5.0.1
npm silly reify moves {}
npm info run magickwand.js@2.0.1 install node_modules/magickwand.js xpm install && xpm run npm-install
npm info run magickwand.js@2.0.1 install { code: 2, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid magickwand.js@2.0.1
npm error code 2
npm error path /root/program/magickwand/node_modules/magickwand.js
npm error command failed
npm error command sh -c xpm install && xpm run npm-install
npm error magickwand.js...
npm error + @xpack-dev-tools/ninja-build@1.11.1-3.1
npm error + @mmomtchev/meson-xpack@1.5.2-4
npm error + @mmomtchev/python-xpack@3.10.15-1
npm error error: Package '@mmomtchev/conan-xpack@2.7.0-1' not found
npm silly unfinished npm timer reify 1730855833795
npm silly unfinished npm timer reify:build 1730855845650
npm silly unfinished npm timer build 1730855845651
npm silly unfinished npm timer build:deps 1730855845651
npm silly unfinished npm timer build:run:install 1730855845735
npm silly unfinished npm timer build:run:install:node_modules/magickwand.js 1730855845736
npm verbose cwd /root/program/magickwand
npm verbose os Linux 6.1.0-26-amd64
npm verbose node v20.18.0
npm verbose npm  v10.8.2
npm verbose exit 2
npm verbose code 2
```

**maybe some failed package else**

```
npm silly placeDep ROOT safe-buffer@5.2.1 OK for: tunnel-agent@0.6.0 want: ^5.0.1
npm silly reify moves {}
npm info run magickwand.js@2.0.1 install node_modules/magickwand.js xpm install && xpm run npm-install
npm info run magickwand.js@2.0.1 install { code: 2, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid magickwand.js@2.0.1
npm error code 2
npm error path /root/program/magickwand/node_modules/magickwand.js
npm error command failed
npm error command sh -c xpm install && xpm run npm-install
npm error magickwand.js...
npm error + @xpack-dev-tools/ninja-build@1.11.1-3.1
npm error error: Package '@mmomtchev/python-xpack@3.10.15-1' not found
npm silly unfinished npm timer reify 1730855565235
npm silly unfinished npm timer reify:build 1730855572991
npm silly unfinished npm timer build 1730855572993
npm silly unfinished npm timer build:deps 1730855572993
npm silly unfinished npm timer build:run:install 1730855573073
npm silly unfinished npm timer build:run:install:node_modules/magickwand.js 1730855573073
npm verbose cwd /root/program/magickwand
npm verbose os Linux 6.1.0-26-amd64
npm verbose node v20.18.0
npm verbose npm  v10.8.2
npm verbose exit 2
npm verbose code 2
```

Environment
 - OS: debian 12 or windows 11
 - node: v20.18.0
 - npm: v10.8.2

**Comment by mmomtchev** [comment]
I cannot reproduce it and it does not look to be a magickwand.js 
problem, it may be an npm registry problem.

What happens if you try to manually install the missing package?Message 
ID: ***@***.***>

**Comment by bobirama** [comment]
> I cannot reproduce it and it does not look to be a magickwand.js problem, it may be an npm registry problem. What happens if you try to manually install the missing package?Message ID: ***@***.***>

Yeah, you are right. I switched to a different registry mirror, and it worked. Thank you!

**Comment by Saraiby** [comment]
> I cannot reproduce it and it does not look to be a magickwand.js problem, it may be an npm registry problem. What happens if you try to manually install the missing package?Message ID: ***@***.***>

Yeah, you are right. I switched to a different registry mirror, and it worked. Thank you!
